//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadingProgram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoadingProgram.ShipData", typeof(ShipData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,9;3081,6;3006,4;3,636;1,022;1769,5;3,904;44662;1569490;14,855;522,0;15,877;117,75;17,70;136,33
        ///2,0;3263,3;3183,7;3,652;1,073;1774,9;3,924;44898;1579732;14,102;496,2;15,176;117,85;17,70;137,22
        ///2,1;3445,4;3361,4;3,667;1,125;1778,6;3,934;45060;1587086;13,405;472,2;14,530;117,94;17,70;137,86
        ///2,2;3628,0;3539,5;3,682;1,177;1782,3;3,944;45224;1594416;12,777;450,5;13,953;118,04;17,70;138,50
        ///2,3;3810,9;3718,0;3,695;1,228;1786,0;3,956;45380;1601708;12,206;430,8;13,434;118,13;17,70;139,13
        ///2,4;3994,2;3896,8;3,70 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HydrostaticsTrim0 {
            get {
                return ResourceManager.GetString("HydrostaticsTrim0", resourceCulture);
            }
        }
    }
}
